version: '3'

services:
  api:
    container_name: api_afinato
    build:
      context: ./API
    ports:
      - "5000:5000"
    restart: always

  web:
    container_name: web_afinato
    build:
      context: ./WEB
    ports:
      - "80:80"
    restart: always